In [17]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.preprocessing import StandardScaler

In [18]:
df = pd.read_csv(r"C:\Users\alokk\Desktop\csv\zoo_data.csv")
df.head()

1  0  0.1  1.1  0.2  0.3  1.2  1.3  1.4  1.5  0.4  0.5  4  0.6  0.7  1.6  \
0  1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1   
1  0  0    1    0    0    1    1    1    1    0    0    1  0    1    0    0   
2  1  0    0    1    0    0    1    1    1    1    0    0  4    0    0    1   
3  1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1   
4  1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1   

   1.7  
0    1  
1    4  
2    1  
3    1  
4    1

In [19]:
x = df.drop(['1.7'],axis = 1)
y = df['1.7']

In [20]:
y = np.array(y)
y

array([1, 4, 1, 1, 1, 1, 4, 4, 1, 1, 2, 4, 7, 7, 7, 2, 1, 4, 1, 2, 2, 1,
       2, 6, 5, 5, 1, 1, 1, 6, 1, 1, 2, 4, 1, 1, 2, 4, 6, 6, 2, 6, 2, 1,
       1, 7, 1, 1, 1, 1, 6, 5, 7, 1, 1, 2, 2, 2, 2, 4, 4, 3, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 7, 4, 1, 1, 3, 7, 2, 2, 3, 7, 4, 2, 1, 7, 4, 2, 6,
       5, 3, 3, 4, 1, 1, 2, 1, 6, 1, 7, 2], dtype=int64)

In [24]:
x = np.array(x)
x_c = StandardScaler().fit_transform(x)

In [26]:
x_train,x_test,y_train,y_test = train_test_split(x_c,y,test_size = 0.2,random_state = 4)

In [27]:
classifier = DecisionTreeClassifier()
classifier.fit(x_train,y_train)

y_pred = classifier.predict(x_test)

In [28]:
print("Accuracy...:",metrics.accuracy_score(y_pred,y_test))

Accuracy...: 0.95


In [29]:
print("Confusion matrix\n", metrics.confusion_matrix(y_pred,y_test))

Confusion matrix
 [[11  0  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  0  1  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  1  2]]


In [30]:
print("Classification Report:\n",metrics.classification_report(y_pred,y_test))

Classification Report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       0.67      1.00      0.80         2
           7       1.00      0.67      0.80         3

    accuracy                           0.95        20
   macro avg       0.94      0.94      0.93        20
weighted avg       0.97      0.95      0.95        20

